type Registration {
  date: String!
  entryId: String!
  firstName: String!
  lastName: String!
  streetAddress: String!
  streetAddress2: String
  city: String!
  state: String!
  zipcode: String!
  phone: String!
  email: String!
  wiaaNumber: String!
  wiaaClass: String!
  officialsAssociation: String!
  crewSize: String
  crewMembers: [String!]
  foodAllergies: String!
  emergencyName: String!
  emergencyNumber: String!
  sessions: [Session]!
  transactionId: String
  paymentAmount: String
  paymentStatus: String
  paymentMethod: String
  cardNumber: String
  isRegistered: Boolean
}

type Query {
  singleRegistration(transactionId: String!): Registration!
  inividualRegistrations: [Registration]!
  hsCrewRegistrations: [Registration]!
  allRegistrations: [Registration]!
}
