type User {
  id: ID!
  email: String!
  password: String!
}

type SignOutSuccessMessage {
  message: String
}

input NewAdminInput {
  email: String!
  password: String!
}

input SignInInput {
  email: String!
  password: String!
}

extend type Query {
  user: User!
  getAllUsers: [User]!
}

type Mutation {
  createAdmin(input: NewAdminInput): User!
  signIn(input: SignInInput!): User
  signOut: SignOutSuccessMessage
}
