type SuccessMessage {
  message: String
}

type User {
  id: ID!
  firstName: String!
  lastName: String!
  phone: String!
  email: String!
  password: String!
}

input NewUserInput {
  firstName: String!
  lastName: String!
  phone: String!
  email: String!
  password: String!
}

input LoginInput {
  email: String!
  password: String!
}

extend type Query {
  getAllUsers: [User]!
  me: User
}

type Mutation {
  signup(input: NewUserInput): User!
  login(input: LoginInput!): User
  logout: SuccessMessage
}
