type User {
  id: ID!
  email: String!
}

input NewAdminInput {
  email: String!
  password: String!
}

input SignInInput {
  id: String!
  password: String!
}

extend type Query {
  user: User!
  getAllUsers: [User]!
  signIn(input: SignInInput!): User
}

type Mutation {
  createAdmin(input: NewAdminInput): User!
}
